name: check and fix

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.json"
      - "scripts/check.py"
      - "scripts/fix_*.py"
      - "scripts/create_rules_markdown.py"
      - ".github/workflows/check-and-fix.yml"

defaults:
  run:
    shell: bash -e {0}

permissions:
  contents: write

jobs:
  check-forbid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.9"
          enable-cache: true

      - name: Check for forbidden file changes
        run: |
          forbidden_files=(
            "rules.md"
            "changelog.md"
            "bilibili-danmu-blocklist-output.json"
          )
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          for file in "${forbidden_files[@]}"; do
            if echo "$changed_files" | grep -q "$file"; then
              echo "Error: Forbidden file $file was modified in this PR. If it's modified by github-actions, please ignore this error."
              exit 1
            fi
          done

  check-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.9"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check the json file
        run: uv run scripts/check.py

  fix:
    if: ${{ github.event_name == 'pull_request' }}
    needs: check-json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.9"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Initialize the dev-environment
        run: |
          pip install ruff
          uv sync --all-extras --dev

      - name: Fix - Format the python files
        run: ruff format

      - name: Fix - Sort the json file
        run: uv run scripts/fix_sort.py

      - name: Fix - Add timestamp to the rules
        run: uv run scripts/fix_id.py

      - name: Create rules.md
        run: uv run scripts/create_rules_markdown.py

      - name: Configure Git
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "has_changed=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: ${{ steps.git_diff.outputs.has_changed == 'true' }}
        run: |
          git add .
          git commit -m "fix: auto fix"
          git pull --rebase origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}

      - name: Push changes
        if: ${{ steps.git_diff.outputs.has_changed == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
