name: fix

on:
  workflow_run:
    workflows: ["check"]
    types:
      - completed
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "scripts/fix.py"
      - "scripts/create_rules_markdown.py"
      - ".github/workflows/fix.yml"

defaults:
  run:
    shell: bash -e {0}

permissions:
  contents: write

jobs:
  fix:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.9"
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Format the python files
        run: ruff format

      - name: Fix the json file
        run: uv run scripts/fix.py

      - name: Create rules.md
        run: uv run scripts/create_rules_markdown.py

      - name: Configure Git
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "has_changed=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: ${{ steps.git_diff.outputs.has_changed == 'true' }}
        run: |
          git add .
          git commit -m "fix: auto fix json file"
          git pull --rebase origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}

      - name: Push changes
        if: ${{ steps.git_diff.outputs.has_changed == 'true' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
